### ISSUE TITLE
polymut.py error reading gff file ?

### ISSUE THREAD

**Issue by tamburinif** [SegataLab/cmseq#4]
Hi there,

I'm trying to run polymut.py on a sorted, indexed bam and gff file output from Prokka as follows:

`polymut.py --mincov 10 --gff_file test_prokka.gff test.bam`

and I am getting the following error:

```
Traceback (most recent call last):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 42, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/bin/polymut.py", line 10, in <module>
    sys.exit(polymut_from_file())
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/cmseq/polymut.py", line 33, in polymut_from_file
    bf.parse_gff(args.gff_file)
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/cmseq/cmseq.py", line 115, in parse_gff
    for rec in GFF.parse(in_handle):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 746, in parse
    target_lines):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 627, in parse
    i = iterator_generator(handle)
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 181, in __init__
    super().__init__(source, alphabet=alphabet, mode="t", fmt="Fasta")
  File "/gstore/scratch/u/tamburif/miniconda3_envs/cmseq/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 46, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given
```

I can confirm that the contig names match between the bam and gff files.

I'm using the latest conda version (1.0) and it would be very helpful to keep using conda so that I can incorporate this analysis into a Snakemake workflow. I did try cloning this repo and running the script from there to try and troubleshoot whether the problem was with the conda version or my specific files, but I got a different error in doing so:

```
Traceback (most recent call last):
  File "/gstore/home/tamburif/tools/cmseq/cmseq/polymut.py", line 6, in <module>
    from .cmseq import CMSEQ_DEFAULTS
ImportError: attempted relative import with no known parent package
```

Your help is much appreciated! Thank you!
Fiona

**Comment by azufre451** [comment]
Hi Fiona, sorry for the long time taken to reply.

Does the same problem happen when installing it from source (note that you have to run: `pip install .` in the source folder, so to be able to run CMSeq correctly.

Can you check which version of bcbio you are using?

```
from BCBio import GFF
GFF.__version__
```

Many thanks,
Moreno

**Comment by tamburinif** [comment]
Hi Moreno, thanks for your reply.

I'm using bcbio v 0.6.6.

When I install from source I get the same error:

`Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
TypeError: expected str, bytes or os.PathLike object, not FakeHandle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gstore/home/tamburif/miniconda3/bin/polymut.py", line 8, in <module>
    sys.exit(polymut_from_file())
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/cmseq/polymut.py", line 32, in polymut_from_file
    bf.parse_gff(args.gff_file)
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/cmseq/cmseq.py", line 115, in parse_gff
    for rec in GFF.parse(in_handle):
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 746, in parse
    target_lines):
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 322, in parse_in_parts
    for results in self.parse_simple(gff_files, limit_info, target_lines):
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 343, in parse_simple
    for results in self._gff_process(gff_files, limit_info, target_lines):
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 637, in _gff_process
    for out in self._lines_to_out_info(line_gen, limit_info, target_lines):
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 699, in _lines_to_out_info
    fasta_recs = self._parse_fasta(FakeHandle(line_iter))
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/BCBio/GFF/GFFParser.py", line 560, in _parse_fasta
    return list(SeqIO.parse(in_handle, "fasta"))
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/gstore/home/tamburif/miniconda3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 51, in __init__
    if source.read(0) != "":
TypeError: read() takes 1 positional argument but 2 were given`

**Comment by azufre451** [comment]
Hi Fiona, 

Apparently this is something due to Biopython's version and its GFF parser. BCBio is fine, but any Biopython newer than 1.76 will cause issues. While we investigate on how to fix this, you will need to run polymut.py in an environment with Biopython with a version older or equal to 1.76.

If you're using pip just install Biopython 1.76 and CMSeq polymut should work fine:

`pip install Biopython==1.76`

Hope this helps. Let me know if you still need help,

Moreno

**Comment by tamburinif** [comment]
Ah, that fixed it. Thank you so much for your help!!
