### ISSUE TITLE
Biopython error with consensus.py

### ISSUE THREAD

**Issue by bishopia** [SegataLab/cmseq#5]
Hi there,

I'm new to cmseq, but it looks like a very recent change to Biopython (Bio.Alphabet removal) has led to the following error. 

```
consensus.py --help
```
```
Traceback (most recent call last):
  File "/users/ibishop/anaconda/proov/bin/consensus.py", line 7, in <module>
    from cmseq.consensus import consensus_from_file
  File "/users/ibishop/anaconda/proov/lib/python3.8/site-packages/cmseq/consensus.py", line 9, in <module>
    from Bio.Alphabet import IUPAC
  File "/users/ibishop/anaconda/proov/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
    raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the ``molecule_type`` as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
```
I installed via bioconda.
Any help or clarification is much appreciated! -i

**Comment by azufre451** [comment]
Hi bishopia,

it seems that this is caused by an incompatible behaviour of CMseq with Biopython 1.78. I changed a few lines and now it should be working.

CMSeq should be available in bioconda soon. In the meantime you can clone it from github and install it with pip by running:`pip install .`
